<?php
/*$tabGenre = array(
'VP'  => 'Voitures particulières',
'TCP' => 'Transports en commun de personnes (Autobus-Autocars-Minibus)',
'CAM' => 'Camions',
'CTTE'=> 'Camionnettes',
'VASP'=> 'Véhicules automoteurs spécialisés',
'TRR' => 'Tracteurs routiers',
'VTST'=> 'Véhicules très spéciaux de transport',
'VTSU'=> 'Véhicules très spéciaux à usages divers',
'MTL' => 'Motocyclettes légères',
'MTT1'=> 'Motocyclettes de puissance intermédiaire',
'MTT2'=> 'Motocyclettes de forte puissance',
'TM'  => 'Tricycles à moteur (transport de personnes)',
'QM'  => 'Quadricycles légers et lourds à moteur',
'MTL1'=> 'Motos légères, de moins de 80 cm3, moins de 75 km/h, automatiques.',
'MTL2'=> 'Motos légères, de moins de 80 cm3, moins de 75 km/h, manuelles.',
'MTL3'=> 'Motos légères, de moins de 125 cm3, moins de 13 Ch. réels.',
'MTTE'=> 'Toutes motocyclettes autres que légères.',
'TQM' => 'Tricycles et quadricycles à moteur',
'MOT1'=> 'Motos légères, de moins de 80 cm3, moins de 75 km/h, automatiques.',
'MOT2'=> 'Motos légères, de moins de 80 cm3, moins de 75 km/h, manuelles.',
'MOT3'=> 'Motos légères, de moins de 125 cm3, moins de 13 Ch. réels.',
'MOTO'=> 'Toutes motocyclettes autres que légères.',
'VELO'=> 'Velo',
);*/

$tabGenre = array(
'VP' =>	'Véhicule particulier',
'VU' =>	'Utilitaire',
'50cc' =>	'Deux roues - 50cc',
'MOTO' =>	'Deux roues - 250cc et +',
'125cc' =>	'Deux roues - 125cc',
'QUADS' =>	'Quads',
'TM' =>	'Trois roues',
'AUTRES' =>	'Autres',
);

$tabEtat = array('vn' => 'VN', 'vo' => 'VO', 'va' => 'VA');

$tabSegment = array(
'ECONOMIQUE',
'INFERIEURE',
'MOY-INFER',
'MOY-SUPER',
'SUPERIEURE',
'LUXE',
'AUTRES',
'INCONNUE',
);

/*$tabEnergie = array(
'AIR COMPRIM'    => 'air comprimé',
'BICARBUR'       => 'bicarburation (essence + autre énergie) (avant 2006)',
'ELEC+ESSENC'    => 'électricité-essence (hybride rechargeable)',
'ESS+G.P.L.'     => 'essence + G.P.L.',
'ESSENCE+HYB'    => 'essence + hybride (hybride non rechargeable)',
'ELECTRIC'       => 'électricité',
'ESS+G.NAT'      => 'essence + gaz naturel comprimé',
'ESSENCE'        => 'essence',
'SUPERETHANOL'   => 'superéthanol1',
'S.ETHAN+G.P.L.' => 'bicarburation superéthanol + G.P.L.',
'ELEC+S.ETHAN'   => 'Electricité + superéthanol',
'S.ETHAN+G.NAT'  => 'bicarburation superéthanol + Gaz naturel',
'FUEL-OIL'       => 'fuel-oil',
'GAZOGENE'       => 'gazogène',
'ESS+GAZO'       => 'essence + gazogène',
'GAZOLE+GAZO'    => 'gazole + gazogène',
'GAZOL+G.NAT+HYB'=> 'mélange de gazole et gaz naturel (dual fuel) et électricité (hybride non rechargeable)',
'GAZOLE+HYB'     => 'gazole + hybride (hybride non rechargeable)',
'ELEC+GAZOLE'    => 'électricité-gazole (hybride rechargeable)',
'GAZ NAT.VEH'    => 'gaz naturel véhicule',
'GAZOLE'         => 'gazole',
'G.P.L.'         => 'gaz de pétrole liquéfié (mélange de butane et propane)',
'CARB GAZEUX'    => 'autres hydrocarbures gazeux comprimés  (sauf  butane et propane)',
'HYDROGENE'      => 'hydrogène',
'ELEC+G.NAT'     => 'électricité-gaz-naturel',
'ELEC+G.P.L.'    => 'électricité-monocarburation GPL',
'PETROL.LAMP'    => 'pétrole lampant  (pour TRA et MAGA uniquement)',
'AUTRES'         => 'autre (avant 2006)',
'INCONNU'        => 'énergie inconnue',
);*/

$tabEnergie = array(
	'ESSENCE' => 'Essence',
	'GASOIL'  => 'Gasoil',
	'ELECTRIQUE' => 'Electrique',
	'HYBRIDE' => 'Hybride',
);

//$tabMarque = getListMarque();

$tabMarque = array(
'ABARTH' => 'ABARTH',
'A.B.C.' => 'A.B.C.',
'AC' => 'AC',
'ACCESS' => 'ACCESS',
'ACE TRADE' => 'ACE TRADE',
'ACL' => 'ACL',
'A.C.M' => 'A.C.M',
'A.C.M.' => 'A.C.M.',
'ACM' => 'ACM',
'A.C.M.A.' => 'A.C.M.A.',
'ACMA' => 'ACMA',
'ACMAT' => 'ACMAT',
'ACREA' => 'ACREA',
'ACURA' => 'ACURA',
'AD.EL' => 'AD.EL',
'ADIVA' => 'ADIVA',
'ADLER' => 'ADLER',
'ADLY' => 'ADLY',
'AEBI' => 'AEBI',
'AEC' => 'AEC',
'AEON' => 'AEON',
'AERMACCHI' => 'AERMACCHI',
'AGF' => 'AGF',
'AGM' => 'AGM',
'AGM MOTORS' => 'AGM MOTORS',
'AGRATI' => 'AGRATI',
'AGRIP' => 'AGRIP',
'AIE' => 'AIE',
'AIGLON' => 'AIGLON',
'AIRSTREAM' => 'AIRSTREAM',
'AIXAM' => 'AIXAM',
'AIYUMO' => 'AIYUMO',
'AJP' => 'AJP',
'AJS' => 'AJS',
'ALCYON' => 'ALCYON',
'ALFA ROMEO' => 'ALFA ROMEO',
'ALKE' => 'ALKE',
'ALLARD' => 'ALLARD',
'A.L.M.' => 'A.L.M.',
'ALMA' => 'ALMA',
'ALP SAITIN' => 'ALP SAITIN',
'ALPHA' => 'ALPHA',
'ALQUIER' => 'ALQUIER',
'ALVIS' => 'ALVIS',
'AMAZONE' => 'AMAZONE',
'A.M.C.' => 'A.M.C.',
'AMERICAN' => 'AMERICAN',
'AMERICAN.M' => 'AMERICAN.M',
'A.M.F.' => 'A.M.F.',
'A.M.G.' => 'A.M.G.',
'AMILCAR' => 'AMILCAR',
'AMS' => 'AMS',
'ANATOLIA' => 'ANATOLIA',
'APAL' => 'APAL',
'APOLLO' => 'APOLLO',
'APRILIA' => 'APRILIA',
'APRO' => 'APRO',
'APTS' => 'APTS',
'AQUILA' => 'AQUILA',
'ARCTIC CAT' => 'ARCTIC CAT',
'ARCUEILMOT' => 'ARCUEILMOT',
);

//$tabModele = getListModele();

$tabModele = array(
	'ALPHA' => array(
		'A FOUR',
		'ABILA',
		'ACADIA',
		'ACADIANE',
		'ACCENT',
		'ACCESBUS',
		'ACCESS',
		'ACCLAIM',
		'ACCORD',
		'ACMA',),
	'AMS' => array(
		'ACTIVE 50',
		'ACTIVE 80',
		'ACTIVE125',
		'ACTROS',
		'ACTY',
		'ACTYON',
		'AC100',
		'AC35',
		'AC35L',
		'AC40CITY',
		'AD 125',
		'AD 250',
		'ADIVA 125',
		'ADIVA 150',
		'ADMIRAL',
		'ADVENTURE',
		'AERA',
		'AEROMAX',
		'AEROSTAR',
		'AEROX',
		'AEROX 100',
		'AERO-8',
		'AE06',),
	'AMILCAR' => array(
		'AE385',
		'AE390',
		'AE400',
		'AE420',
		'AE430',
		'AE520',
		'AE560',
		'AGIL CITY',
		'AGILA',
		'AGILITY',
		'AGORA',
		'AGROTK410',
		'AG100',
		'AG300',
		'AH',
		'AH100',
		'AH50',
		'AH80',
		'AIRTECH',
		'AK',
		'ALAZZURA',
		'ALEKO',
		'ALERO',
		'ALFA 33',
		'ALFA 6',
		'ALFA 75',
		'ALFA 90',
		'ALFASUD',
		'ALFETTA',
		'ALHAMBRA',
		'ALIEN',
		'ALIZEE',
		'ALLANTE',),
	'AMAZONE' => array(
		'ALLEGRO',
		'ALLROAD',
		'A.L.M.',
		'ALMERA',
		'ALOUETTE',
		'ALP 125',
		'ALP 200',
		'ALP 250',
		'ALP 4.0',
		'ALP 400',
		'ALPICRABE',
		'ALPINA',
		'ALPINE',
		'ALPIROUTE',
		'ALTEA',
		'ALTER',
		'ALTINO',
		'ALTO',
		'ALTV',
		'ALYOS',
		'AMAROK',
		'AMI',
		'AMIGO',
		'AMPERA',
		'ANF125',
		'ANTARA',
		'AN125',
		'AN250',
		'AN400',
		'AN400K2',
		'AN650',
		'AP 50',),
	'AGRIP' => array(
		'APE CLASS',
		'APE 125',
		'APE 190',
		'APE.CALES',
		'APL125L',
		'APL50QL',
		'APPLAUSE',
		'AP201',
		'ARAGON',
		'ARDILA',
		'ARENA',
		'ARES',
		'ARGENTA',
		'ARIANE',
		'ARIES',
		'ARK AIR C',
		'ARK LIQ C',
		'ARNAGE',
		'ARN125',
		'ARO',
		'ARONDE',
		'AROSA',
		'ARPEGE',
		'ARROW 250',
		'ARWAY',
		'AR80',
		'ASCONA',
		'ASTRA',
		'ASTRO',
		'ASX',
		'AS51',
		'AT',)
);

/*$tabCarrosserie = array(
'BERLINE ',
'BREAK ',
'COUPE',
'CABRIOLET',
'FOURGON ',
'FOURGONNETTE ',
'MINIBUS ',
'PICK-UP',
'MONOSPACE ',
'MONOSPACE  COMPACT',
'MINISPACE ',
'COMBISPACE',
'TS TERRAINS / CHEMINS ',
'BENNE BASCULANTE ',
'CHASSIS ',
'TRACTEUR ROUTIER ',
'BUS-CAR ',
'AMBULANCE ',
'CAMPING-CAR ',
'MINI-CAR',
'PLATEAU ',
'AUTRES CARROSSERIES ',
'INCONNUE ',
'TOUS TERRAINS',
'ROUTIÈRES',
'SCOOTERS',
'QUADRICYCLES',
'TRICYCLES',
'CUSTOM CHOP',
'QUADS',
);*/
$tabCarrosserie = array(
'BER' =>	'Berline',
'MONO' =>	'Monospace',
'BREAK' =>	'Break',
'TS_TERR' =>	'Tous terrains / SUV',
'FOURGON' =>	'Fourgon et fourgonnettes',
'SCOOTERS' =>	'Scooters',
'MOTO_ROUTE' =>	'Moto routieres',
'COUPE' =>	'Coupé',
'CABRIOLET' =>	'Cabriolet',
'AUTRES' =>	'Autres',
'MOTO' => 'TT	Moto tous terrains',
'CAMPINGCAR' =>	'Camping car',
'MINIBUS' =>	'Minibus',
'QUADS' =>	'Quads',
'MOTO_SPORT' =>	'Moto sportives',
'MOTO_CUST' =>	'Moto custom',
'MOB' =>	'Mobylettes',
'CAMION' =>	'Camion',
);

$tabPrix = array(
3000 => '3 000 €',
4500 => '4 500 €',
6000 => '6 000 €',
7500 => '7 500 €',
9000 => '9 000 €',
10500 => '10 500 €',
12000 => '12 000 €',
13500 => '13 500 €',
15000 => '15 000 €',
16500 => '16 500 €',
18000 => '18 000 €',
19500 => '19 500 €',
21000 => '21 000 €',
22500 => '22 500 €',
24000 => '24 000 €',
25500 => '25 500 €',
27000 => '27 000 €',
28500 => '28 500 €',
30000 => '30 000 €',
31500 => '31 500 €',
33000 => '33 000 €',
34500 => '34 500 €',
36000 => '36 000 €',
37500 => '37 500 €',
39000 => '39 000 €',
40500 => '40 500 €',
42000 => '42 000 €',
43500 => '43 500 €',
45000 => '45 000 €',
46500 => '46 500 €',
48000 => '48 000 €',
49500 => '49 500 €',
51000 => '51 000 €',
52500 => '52 500 €',
54000 => '54 000 €',
55500 => '55 500 €',
57000 => '57 000 €',
58500 => '58 500 €',
60000 => '60 000 €',
61500 => '61 500 €',
63000 => '63 000 €',
64500 => '64 500 €',
66000 => '66 000 €',
67500 => '67 500 €',
69000 => '69 000 €',
70500 => '70 500 €',
72000 => '72 000 €',
73500 => '73 500 €',
75000 => '75 000 €',
76500 => '76 500 €',
78000 => '78 000 €',
79500 => '79 500 €',
81000 => '81 000 €',
82500 => '82 500 €',
84000 => '84 000 €',
85500 => '85 500 €',
87000 => '87 000 €',
88500 => '88 500 €',
90000 => '90 000 €',
91500 => '91 500 €',
93000 => '93 000 €',
94500 => '94 500 €',
96000 => '96 000 €',
97500 => '97 500 €',
99000 => '99 000 €',
100500 => '100 500 €',
);

if (!isset($_SESSION['_vehicules'])) {
	$_SESSION['_vehicules'] = array();
}
$tabVehicules =& $_SESSION['_vehicules'];

if (!isset($tabVehicules['inclus'])) {
	$tabVehicules['inclus'] = array();

	$criteria = array(	'marque' => array('value' => 'renault', 'label' => 'Renault'),
						'modele' => array('value' => 'r5', 'label' => 'r5'),
						'mec' => array('min' => '01/1991'));
	$tabVehicules['inclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'genre' => array('value' => 'VP', 'label' => 'Véhicule particulier'),
						'marque' => array('value' => 'renault', 'label' => 'Renault'),
						'modele' => array('value' => 'r21', 'label' => 'R 21'),
						'mec' => array('min' => '01/1991', 'max' => '05/1995'));
	$tabVehicules['inclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'marque' => array('value' => 'citroen', 'label' => 'Citroën'),
						'modele' => array('value' => 'ds', 'label' => 'DS'),
						'ddi' => array('min' => '05/2011'),
						'parg' => array('min' => '8000'));
	$tabVehicules['inclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'marque' => array('value' => 'ferrari', 'label' => 'Ferrari'),
						'ddi' => array('min' => '01/2009', 'max' => '12/2012'),
						'parg' => array('min' => '20000', 'max' => '120000'));
	$tabVehicules['inclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'genre' => array('value' => 'MOTO', 'label' => 'Deux roues - 250cc et +'),
						'carrosserie' => array('value' => 'MOTO_CUST', 'label' => 'Moto custom'),
						'etat' => array('value' => 'VA', 'label' => 'Véhicule assimilé neuf'));
	$tabVehicules['inclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	/*$tabVehicules['inclus'] = array(
		array(
			'marque' => array('value' => 'renault', 'label' => 'Renault'),
			'modele' => array('value' => 'r5', 'label' => 'r5'),
			'mec' => array('min' => '01/1991')
		),
		array(
			'genre' => array('value' => 'VP', 'label' => 'Véhicule particulier'),
			'marque' => array('value' => 'renault', 'label' => 'Renault'),
			'modele' => array('value' => 'r21', 'label' => 'R 21'),
			'mec' => array('min' => '01/1991', 'max' => '05/1995')
		),
		array(
			'marque' => array('value' => 'citroen', 'label' => 'Citroën'),
			'modele' => array('value' => 'ds', 'label' => 'DS'),
			'ddi' => array('min' => '05/2011'),
			'parg' => array('min' => '8000')
		),
		array(
			'marque' => array('value' => 'ferrari', 'label' => 'Ferrari'),
			'ddi' => array('min' => '01/2009', 'max' => '12/2012'),
			'parg' => array('min' => '20000', 'max' => '120000')
		),
		array(
			'genre' => array('value' => 'MOTO', 'label' => 'Deux roues - 250cc et +'),
			'carrosserie' => array('value' => 'MOTO_CUST', 'label' => 'Moto custom'),
			'etat' => array('value' => 'VA', 'label' => 'Véhicule assimilé neuf')
		),
	);*/
}
if (!isset($tabVehicules['exclus'])) {
	$tabVehicules['exclus'] = array();

	$criteria = array(	'marque' => array('value' => 'renault', 'label' => 'Renault'),
						'modele' => array('value' => 'r32', 'label' => 'r32'),
						'mec' => array('max' => '01/1995'));
	$tabVehicules['exclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'energie' => array('value' => 'diesel', 'label' => 'Diesel'),
						'mec' => array('max' => '01/1999'));
	$tabVehicules['exclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	$criteria = array(	'genre' => array('value' => 'CAMION', 'label' => 'Camion'),
						'segment' => array('value' => 'INFERIEURE', 'label' => 'Inférieur'),);
	$tabVehicules['exclus'][] = array('criteria' => $criteria, 'hash' => getHashCriteria($criteria));

	/*$tabVehicules['exclus'] = array(
		array(
			'marque' => array('value' => 'renault', 'label' => 'Renault'),
			'modele' => array('value' => 'r32', 'label' => 'r32'),
			'mec' => array('max' => '01/1995')
		),
		array(
			'energie' => array('value' => 'diesel', 'label' => 'Diesel'),
			'mec' => array('max' => '01/1999')
		),
		array(
			'genre' => array('value' => 'CAMION', 'label' => 'Camion'),
			'segment' => array('value' => 'INFERIEURE', 'label' => 'Inférieur'),
		),
	);*/
}